version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Prudhviraj@310'
      MYSQL_DATABASE: 'ecommerce_db'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-network

  backend-api:
    # USE THE IMAGE JENKINS PUSHED
    image: prudhviraj310/ecommerce-backend:latest
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=Prudhviraj@310
      - DB_NAME=ecommerce_db
    depends_on:
      - db
    restart: always
    networks:
      - ecommerce-network

  frontend-app:
    # USE THE IMAGE JENKINS PUSHED
    image: prudhviraj310/ecommerce-frontend:latest
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    restart: always
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql_data: