version: '3.8'

services:
  # --- DATABASE SERVICE ---
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Prudhviraj@310'
      MYSQL_DATABASE: 'ecommerce_db'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # --- BACKEND SERVICE ---
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db  # Tells backend to use the 'db' service above
      - DB_USER=root
      - DB_PASS=Prudhviraj@310
      - DB_NAME=ecommerce_db
    depends_on:
      - db
    restart: always

  # --- FRONTEND SERVICE ---
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # NOTE: Ensure this IP matches your current AWS Public IP
        - REACT_APP_API_URL=http://13.201.34.71:5000/api
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    restart: always

volumes:
  mysql_data: